services:
  - type: web
    name: trendly-agentic-support-assistant
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: TRENDLY_MODEL
        value: openai/gpt-oss-120b
      - key: REDIS_URL
        fromService:
          type: redis
          name: trendly-redis
          property: connectionString
      - key: ADMIN_KEY
        sync: false

  - type: redis
    name: trendly-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
